### ISSUE TITLE
extend information sent to da|ra

### ISSUE THREAD

**Issue by MarenStephan** [dzhw/metadatamanagement#1147]
include data curators + other metadata?
TODO for Sowis: define the metadata which should be registered at da|ra and identify the necessary da|ra elements

**Comment by rreitmann** [comment]
@kpstephan define additional attributes especially check which attributes need to be added to our domain model...

**Comment by rreitmann** [comment]
@dkatzberg: Here are my first review remarks:
- [ ] Do not load all variables for the template just in order to count them
- [ ] Double check all ifs in the template (you need at least one additional if for study.annotations.de)
- [ ] Before you open list tags you have to check that the list is not empty (see dataSets)

**Comment by rreitmann** [comment]
@dkatzberg see https://github.com/dzhw/metadatamanagement/pull/1389#pullrequestreview-75729448
