### ISSUE TITLE
switch attribute citationHint from study details page to dataSet details page?

### ISSUE THREAD

**Issue by MarenStephan** [dzhw/metadatamanagement#1150]
the current attribute citationHint contains the citation of the used dataSets not the citation of the study of the "Primärforschungsprojekt"
- do we need two different citations (study details page and dataSets details page) or only the current citation switched to dataSet details pages?
involve @svietgen for initial ideas of citation-String on dataset details page

**Comment by MarenStephan** [comment]
also discuss if it even makes sense to translate the german citationHint to english

**Comment by rreitmann** [comment]
@kpstephan needs further input...

**Comment by rreitmann** [comment]
Remark: study.citationHint is allready an I18nString.. (definable in both languages)

**Comment by svietgen** [comment]
yes, we want to switch the attribute citationHint from study details page to dataSet details page

**Comment by rreitmann** [comment]
To clarify:
We will move citationHint from study to **SubDataSet**. It will be displayed truncated in the table on the dataset details page with a copy to clipboard button.

**Comment by rreitmann** [comment]
@dkatzberg  Here are my review remarks:
- data-set-citate-dialog is not a directive (data-set-citate-dialog.*.js have to be moved to views)
- modal dialogs must not be opened by a link, use an md-button (md-icon-button with https://material.io/icons/#ic_format_quote) 
- currently citation links cannot be navigated with keyboard (should be fixed with the above item)

**Comment by dkatzberg** [comment]
@rreitmann the enabled icon is very similar to the disabled icon... i think we should discuss this.

**Comment by rreitmann** [comment]
@svietgen Should be fixed now...
