### ISSUE TITLE
as publisher I want to switch from a variable details page to the next variable details page

### ISSUE THREAD

**Issue by MarenStephan** [dzhw/metadatamanagement#1180]
it is very helpful when you has to check all variable details pages of a dataset
variable pages ordered like in dataset or alphabetical? (evt. order of importfile variables.xslx)

I'm not sure, if it's also a feature for users

**Comment by rreitmann** [comment]
After a short discussion we think that we should use the row number of the variables.xlsx as variable.indexInDataSet. Then we can offer a static link to the next variable in the dataSet on the variableDetails page.

**Comment by rreitmann** [comment]
@svietgen Do you think this is more important (prio:2)?

**Comment by svietgen** [comment]
@rreitmann Yes, I think it's more important.

And I think it's a good idea to use the row number of the variables.xlsx (not alphabetical).

**Comment by dkatzberg** [comment]
- [ ] Update Variable Interface
- [ ] Update Wiki Page
- [ ] Update Import, Index of Dataset.Variablelist is now automatic maintaining
- [ ] Update Detailspage (comparable with question detail page)

**Comment by dkatzberg** [comment]
@svietgen We have to discuss one "issue". Let me explain it on an example, please.

I have my variables Excel Sheet and I upload it. The sheet has 5 variables. There are some validation errors on the third variable and the variable wasn't saved into in the database. Now I visit the details page of the variable with the indexinDataSet = 1 and I click "next". On the Variable with indexInDataSet = 2 is no "next" variable, because the third one wasn't successfully uploaded, but the forth and fifth are still available. What should we do in this case?

**Comment by rreitmann** [comment]
@dkatzberg Please have a look at my changes cause I had to change a few things:
1. This feature is relevant for all users (not only publishers)
2. The index in mongo db was recreated on server startup cause you haven't changed it's definition in Variable.java
3. There have been a few spelling errors
4. It is not necessary to recreate elasticsearch indices for this feature (see #1245)
