### ISSUE TITLE
Improve feedback button

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1247]
We should predefine labels and content of the issues created through our application. This be done by enriching the link in the navigation menu like this:
https://github.com/dzhw/metadatamanagement/issues/new?body=%0A---------------------------------%0AQuelle%3A%0Ahttps%3A%2F%2Fmetadatamanagement-dev.cfapps.io%2F%23!%2Fde%2Fsearch%3Fpage%3D1%26type%3Dstudies%26data-set%3Ddat-testssy19-ds1%24&labels=type:bug

**Comment by svietgen** [comment]
When I'm on the dataset search page and use the feedback button the issue gets the crosscutting-label (instead of datasetmanagement).

When I test the feedback button with internet explorer 11 I get this error message:
![fehlermeldung](https://user-images.githubusercontent.com/22055122/28357204-eae1407e-6c6a-11e7-8552-2b25f6826975.jpg)

**Comment by svietgen** [comment]
Do we need the translated term "source" for international users?

**Comment by dkatzberg** [comment]
should be fixed by the issue #1240 and i added the translation for source and quelle
