### ISSUE TITLE
change title of search system

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1255]
when I bookmark the search system on my desktop computer or get an icon on my mobile device the title of the search systen is "Metadatensuche". I think we should change this to something more fdz related.

As I don't think many people can relate to metadata - my proposal:
FDZ-DZHW Suchsystem

edit: I recommend not to use _meta_ in the title as users acually want to find data, not metadata

**Comment by rreitmann** [comment]
FDZ-DZHW Metadatensuche

**Comment by rreitmann** [comment]
@AndyDaniel1 @kpstephan Please define a name for the system which users can understand...

**Comment by UteH** [comment]
@kpstephan: We should/could ask @schellep how we refer to the search system so far in our roll-ups, flyer materials etc.

**Comment by schellep** [comment]
A preliminarey suggestion (we use in the website) is: 
 - "Search Portal"/"Suchportal" (short, eg. for browser) 
 - "Search Portal for available data sets"/"Suchportal zu den verfügbaren Datensätzen" (more explanatory)
- "Search Portal for available data sets as well as variables and characteristics" (even more explanatory)

I'am open for any discussion...

**Comment by UteH** [comment]
@rreitmann mentioned that we are actually moving towards a metadata management system by making study detail page editable

**Comment by rreitmann** [comment]
During our review on Monday we have discussed the following:
1. Changing the title of the system (Metadatamanagement aka MDM) would lead to many inconsistent links since they contain the string metadata. Fixing these links would be really cumbersome.
2. If we keep the name of the system we will need a subtitle in german and english which roughly summarizes the purpose of the system for public users.
3. We suggest the following subtitle:
de: Datensuche für die Hochschul- und Wissenschaftsforschung
en: Data Search for higher education research and science studies

@fbaillet @anneweber Please, let us know your thoughts on this within this week.

**Comment by fbaillet** [comment]
@rreitmann sounds reasonable :) (:+1:

**Comment by UteH** [comment]
so we also [keep the fdz logo](https://github.com/dzhw/metadatamanagement/issues/1423)?

**Comment by rreitmann** [comment]
I would prefer the logo with the mag glass above the D of DZHW....

**Comment by rreitmann** [comment]
@rbirkelbach Please test this

**Comment by schellep** [comment]
@rreitmann @dzhw/sowis before I use it on the website or open an new Issue - to add this in [wiki](https://github.com/dzhw/FDZ_Allgemein/wiki/Redaktionelle-Standards) - is [this](https://github.com/dzhw/metadatamanagement/issues/1255#issuecomment-407367757) - fix now?

 de: Datensuche für die Hochschul- und Wissenschaftsforschung 🇩🇪 
 en: Data Search for higher education research and science studies 🇬🇧

**Comment by rreitmann** [comment]
@schellep since the issue has been closed, it is fix (for now)

**Comment by schellep** [comment]
@rreitmann, thanks, so [I ask @liedtke-dzhw](https://github.com/dzhw/FDZ_Allgemein/issues/323) to put this information in our [wiki](https://github.com/dzhw/FDZ_Allgemein/wiki/Redaktionelle-Standards).
