### ISSUE TITLE
As publisher i want to edit study details in a form

### ISSUE THREAD

**Issue by kpstephan** [dzhw/metadatamanagement#1416]
The edit study page is an seperate page beside the details page
We need the following functions:

- [x] New Study
- [x] Edit Study
- [x] Delete Study
- [x] Add Attachment
- [x] Delete Attachment
- [x] German and English on one page
- [x] Client validation
- [x] Edit only, if the study is not released

**Comment by dkatzberg** [comment]
@rreitmann 
Feedback:
- [ ] Study Search Result List; Project is choosen and Study exists: The "new" button should be an edit button
- [ ] Missing I18nStrings: ...tooltip.add-author, ...tooltip.move-author-up, ...tooltip.move-author-down

**Comment by rreitmann** [comment]
@dkatzberg I have fixed the issues you have mentioned as well as two additional ones....

**Comment by dkatzberg** [comment]
@rreitmann add an information to the "new study" page at the end of the page. the string should be something like "you can add attachments after creation of an study"

**Comment by kimsommer** [comment]
**In General:**
- Erhebungsreihe and Survey Series should be changed to Studienreihe/Study Series -> descriptive text is already correct
- Change Erhebungsdesign/Survey Design to Studiendesign/ Study Design?
- descriptive text institution: change Erhebungen/surveys to Studie/study?
- Name of Card "Projektmitarbeiter(innen)" in English "Authors" -> maybe better "Project Members"?
- Text Institution: Not "If available" because other mandatory fields don't have that either
- Studienbeschreibung text is is inconsistent: (auf Deutsch) "... Beschreibung der Studie...", (auf Englisch) "... Beschreibung zur Studie..."
- I think in English also adjectives related to nationalities are written with capital letters (in descriptive text of  Institution and Sponsored by)
- New Survey Series text: ""No survey series found!" -> sounds like it is not allowed to add a new survey series, maybe "No existing study is related to this series." or something similar
- Mandatory * for fields where only one language is required is sometimes visible in one field and sometimes in both fields -> I find it a bit confusing. Maybe the text "must not be empty at least for one language" can already be added somewhere.
- when something is filled in incorrectly it is not possible to save the study but the error is not immediately visible for the user -> from other forms I know that it is possible to click save and afterwards the fields which are filled incorrectly are marked red
- why is it not possible to change the language during editing?
- modify/add document dialog: description is mandatory but no *

**Cases:**
- Study was edited, changes aren't saved -> Click FDZ Logo -> Dialog box: Discard changes? -> Click Button No -> Click FDZ Logo a 2nd time -> nothing happens

**IE:**
- Cards Authors and Documents related to Study overlap
- No whitespace at the bottom of page: buttons overlap documents related to study
--> even worse when browser window is small
- Authors: project members cannot be moved up or down
- Documents related to study: no new documents can be added, old documents cannot be edited

**Firefox:**
- Documents related to study: Add new document and Modify document dialog miss the save button

**Github:**
- Authors with First Middle and Last Name
- StudyAttachmentMetadata: title is missing
