### ISSUE TITLE
Variable-generation: implement csv import for missing conditions

### ISSUE THREAD

**Issue by kimsommer** [dzhw/metadatamanagement#1577]

**Comment by rreitmann** [comment]
@kimsommer, @rbirkelbach Here are my remarks:
- [ ] We need to document what can be achieved with the missing conditions and what is currently not possible (focus on having operators concatenated with or)
- [ ] there should be an input script dedicated to missing conditions (like the other inputs)
- [ ] the data set import script should already evaluate missing conditions so that we generate a cleaned data frame only once (this should improve the performance!)

Get in touch with me to discuss this...

**Comment by kimsommer** [comment]
@rbirkelbach Please copy the documentation for missing conditions to [this wiki entry](https://github.com/dzhw/metadatamanagement-io/wiki/variables), after this issue is implemented.

## Missing Conditions

In der Exceltabelle **missingConditions.xlsx**  können für numerische und string Variablen Missingbedingungen angegeben werden. Die Exceltabelle enthält die beiden Tabellenblättern *missingConditionNumeric* und *missingConditionString*. Es ist möglich für numerische und string Variablen jeweils mehrere Bedingungen anzugeben. Die Bedingungen werden mit **ODER** verknüpft. Das heißt, wenn eine der Bedingungen für einen Wert zutrifft, wird dieser Wert als Missing gewertet.  Die verfügbaren Operatoren können in der Exceltabelle über ein Drop-Down Menü ausgewählt werden und sind im Tabellenblatt *list of valid operators* dokumentiert. 

 #### Beispiel Tabellenblatt: *missingConditionNumeric*

| operator | value |
| ---------  | ------ |
| less than or equal to | -800 |
| equal to | 99 |

#### Beispiel Tabellenblatt: *missingConditionString*

| operator | value |
| ---------- | ------ |
| equal to | -966 nicht bestimmbar |
| equal to | -968 unplausibler Wert |

#### Tabellenblatt: *list of valid operators*

| operators for numeric variables | operators for string variables |
| ------ | ------ |
| less than | equal to |
| greater than | not equal to |
| less than or equal to | |
| greater than or equal to | |
| equal to | |
| not equal to | |

**Comment by rreitmann** [comment]
@rbirkelbach see https://github.com/dzhw/metadatamanagement/issues/1577#issuecomment-382660292
