### ISSUE TITLE
Implement automatic tests for data providers

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#1642]

**Comment by YPeper** [comment]
Trying to build a test for the workflow of creating a study. Problems due to not being able to click the drop-down menus survey design and data availability. Also problematic is the button to edit or add a study: you need to mouse over the button in the bottom right corner, but firefox can't do "mouse over". Button can't be clicked as it would push the opened menu away.

**Comment by YPeper** [comment]
To-Do:
- Create Survey page: data driven test
- Create Study page: workflow
- Fileupload

**Comment by YPeper** [comment]
@rreitmann Please review my tests/changes. Last build failed but not due to test problems but this random failure in edge at the last test case.
