### ISSUE TITLE
As a member of the devops team I want the code of the mdm to be citeable and have a doi

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#1709]
https://guides.github.com/activities/citable-code/

**Comment by AndyDaniel1** [comment]
@UteH this is a great idea as we would have a consistent MDM/Documentation relation. The only obstacle I see here is the automation process since the versioning of the manual would be done manually, right? We have to estabilish a process for this (maybe initiated via a hint in the release process "please update the version of the mdm-documentation to "X.X."). Or the Scrum Master is responsible by default. Maybe there exists a possibility to completly automate the process of versioning the documentation.

**Comment by UteH** [comment]
and maybe #1659 could also be helpful
