### ISSUE TITLE
As a publisher I want to deliver keywords describing studies to the VFDB

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#1800]
For the Verbund Forschungsdaten Bildung (VFDB) we need to tag our studies with keywords. The "thesaurus" (FIS Bildung) is not perfect for our field of research but we can can also use free keywords.

For now, we will deliver the metadata manually into their system. The queston is, do we want to use the keywords "individually" and to add these to the MDM aswell?

**Comment by rreitmann** [comment]
We need a new field study.tags containing an array of I18nString(s)....

**Comment by rbirkelbach** [comment]
- when clicking on a tag the mdm does not find studies with the tag
- The input field is cut off after 24 characters, which looks weird.

**Comment by rbirkelbach** [comment]
tags get lost after release but are still in the json and get successfully delivered to dara

**Comment by es-flavia** [comment]
It seems ElasticSearch data was stale. Reindexed it. Tags should appear now. We should discuss the input field width tomorrow. It's handled by the md-autocomplete directive internally and I don't want to mess with it.

**Comment by rbirkelbach** [comment]
The input field width is not too important in my opinion, but I wanted to share my impression nevertheless. Form follows function and if the form potentially destroys the functionality we should just leave it unless the product owner decides otherwise.

________________________________
Von: es-flavia <notifications@github.com>
Gesendet: Dienstag, 26. März 2019 16:44
An: dzhw/metadatamanagement
Cc: Birkelbach, Robert; Comment
Betreff: Re: [dzhw/metadatamanagement] As a publisher I want to deliver keywords describing studies to the VFDB (#1800)


It seems ElasticSearch data was stale. Reindexed it. Tags should appear now. We should discuss the input field width tomorrow. It's handled by the md-autocomplete directive internally and I don't want to mess with it.

-

**Comment by rreitmann** [comment]
@rbirkelbach Please retest there is #2123 for the input witdth...

**Comment by rbirkelbach** [comment]
The input width is still the same in FF 66.0.1 (64-bit) and Chromium 73.0.3683.75. I didn't test ie/edge, because I suppose it'll be the same

**Comment by rbirkelbach** [comment]
Still, if I click a tag, I don't see the studies with the respective tag.

**Comment by rreitmann** [comment]
@rbirkelbach Communication is difficult these days :(
Reindexing of elasticsearch for the tags was missing. Should work now. Input width was not changed, we will take care of it in #2123.

**Comment by rbirkelbach** [comment]
keywords get delivered, are searchable but aren't shown to publishers and data providers

**Comment by rbirkelbach** [comment]
cannot reproduce anymore. weird.
