### ISSUE TITLE
Variablereport: variable "fsport" no additionalQuestionText shown

### ISSUE THREAD

**Issue by rbirkelbach** [dzhw/metadatamanagement#2254]

**Comment by rreitmann** [comment]
@UteH, @rbirkelbach: We have never shown the additional question text in the template. Instead we show `variable.relatedQuestion.relatedQuestionStrings`. This is due to the fact that the complete `additionalQuestionText` might contain many things which belong to other variables of the same question but do not belong to the variable being documented. What shall we do?
