### ISSUE TITLE
As public User I cannot see the instruments of ssy21 although they are released

### ISSUE THREAD

**Issue by UteH** [dzhw/metadatamanagement#2282]
https://metadata.fdz.dzhw.eu/#!/de/studies/stu-ssy21$?version=2.0.0 

Rerelease fixed the problem. But why

**Comment by rreitmann** [comment]
Hmm, last rerelease must have been 8 days ago within #2275. However I can only see the logs of the last 5 days :(

**Comment by anneweber** [comment]
For the SE21 the problem seems to be fixed. But there seems to be a similar problem with gra 2009:
- https://metadata.fdz.dzhw.eu/#!/de/search?page=1&type=instruments&study=stu-gra2009$-1.0.1
- https://metadata.fdz.dzhw.eu/#!/de/search?page=1&type=data_sets&study=stu-gra2009$-1.0.1
(Thanks @svietgen )

**Comment by rreitmann** [comment]
I can see that the shadow copies exist in mongo DB, however apparently they are not present in elasticsearch. I will reindex elasticsearch this evening in order to see whether that helps. #2246 becomes more urgent due to this...

**Comment by AndyDaniel1** [comment]
This should be fixed soon. As mentioned in #2246 I lack the deeper understanding if the refactoring is the solution to this issue.

**Comment by rreitmann** [comment]
A reindex of elasticsearch fixed the problem for the time being...
