### ISSUE TITLE
Specify the conditions we would expect from the VFDB-API 

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#2384]
The VFDB has asked us to specify the conditions that we would expect from the API. Let us discuss this topic in the next few weeks.

**Comment by rreitmann** [comment]
- REST API with OpenAPI Documentation (fka Swagger)
- Health Endpoint for checking whether the service is alive
- Test system for testing integrations

**Comment by polx** [comment]
So.
Do I understand properly that: 

- the encoding that goes through the rest api does not matter (xml, json, rdf, yml, ...)
- the nature of the exchanged information remains to be defined

?

thanks

**Comment by rreitmann** [comment]
@polx 
- We would prefer JSON (utf-8 encoded) as representation of the resources
- use a standardized authentication scheme (e.g. http basic over ssl)
- the schema of the resources depends on the data you want to collect, we can review it as soon as you have an OpenAPI like documentation

**Comment by polx** [comment]
We have a clear case of the function of an OAI-PMH provider Endpoint. This is a form of REST interface but whose protocol was created even before the word REST was coined. My problem is that I found no OpenAPI effort yet that describes OAI-PMH.

(part of the fun is that the OpenAPI-Initiative calls itself OAI which is quite irrespectful).

**Comment by rreitmann** [comment]
I have not been aware of [OAI](http://www.openarchives.org/OAI/openarchivesprotocol.html) yet. Have to look into it....

**Comment by polx** [comment]
How is the look going?

**Comment by rreitmann** [comment]
Sorry, here are my remarks:
- OAI-PMH uses HTTP as transport protocol but does not leverage the semantics of HTTP (URLs=nouns, HTTP-methods=verbs) thus I would not call it RESTful and there will be no simple OpenAPI-Doc generation
- My first impression is that our role in the OAI-PMH model would be "repository" thus we would need to implement an interface for the harvester, which we have currently not planned
- From the documentation I cannot identify the endpoint/verb to which we would send our metadata

**Comment by polx** [comment]
Hello @rreitmann : Well, I disagree with the non-RESTful interpretation.
POSTing or GETting a request is just as much a resource request. The fact that the term _verb_ is used at the OAI-PMH level does not mean that it needs to be the same concept as the verb of the REST world (which is tightly bound to a CRUD interpretation which has no place as far as I can tell).

In our case, considering sizes, I think that using GET is rather good practice as it makes things a tick more cache-friendly and we are far from overloading the length of URLs.

As to who is a repository and who is a provider. I think that it is not unlikely that we both are both at least after some time. Or?

**Comment by rreitmann** [comment]
@polx I think it is not important to argue about RESTfullness at this moment. But OAI-PMH is quite similar to SOAP and https://stackoverflow.com/questions/1950764/why-isnt-soap-based-web-service-restful

The important thing is to clarify the roles and therefore who implements what. In OAI-PMH terms we would be one Data Provider and you would be a Service Provider offering "value-added services" with the metadata harvested from the Repositories of all Data Providers. The Repositories implement the protocol as defined [here](http://www.openarchives.org/OAI/openarchivesprotocol.html#ProtocolMessages) so that the harvester can retrieve the records from the Repository and store it for the Service Provider. 

Implementing that protocol on our side is far more complicated then simply PUTting our metadata (aka as data module, data package,...) in one HTTP endpoint offered by you (like da|ra) does. That way we can create and update the metadata on your side on every release of a data package. Furthermore it is much more efficient sending you only the data which has changed instead of getting harvested regularly although nothing has changed.

**Comment by rreitmann** [comment]
Here are some tools which would help implementing the Repository Endpoints:
http://www.openarchives.org/pmh/tools/
