### ISSUE TITLE
As dataprovider or publisher I want to create/edit analyis packages in the project cockpit

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2978]
- project configuration: either data package or analysis package
- exactly one analysis package
- analysis package needs to be versioned with javers

some fields are already defined here:
https://github.com/dzhw/metadatamanagement/issues/2952

domain model needs to be defined

**Comment by rreitmann** [comment]
- project cockpit: project configuration must not allow deselect of publications if analysis package is selected (disable checkbox)
- project cockpit: click on "Löschen"-Button of analysis packages in German, shows english are you sure dialog
- project cockpit: card alignment is strange should we remove empty cards?
- edit/create: sponsors and institutions must not be mandatory, start with empty list, allow deletion of last entry (same as analysisDataPackages)
- edit/create: scripts must not be empty, start with list with one empty entry, do not allow deletion of last entry
- edit/create: Hint for title contains "deutsch/englisch" twice: "Geben Sie den deutschen Titel des Analysepakets auf Deutsch ein."
- edit/create: the breadcrumb on the top of the page is missing (compare with data package)
- edit/create: order of the cards: details, description, authors, data curators, institutions, sponsors, license, scripts, analyzed data packages (rename title), tags, additional links, attachments
-

**Comment by MIKAGMR** [comment]
- [ ]     project cockpit: project configuration must not allow deselect of publications if analysis package is selected (disable checkbox)
- [ ]     project cockpit: click on "Löschen"-Button of analysis packages in German, shows english are you sure dialog
- [ ]     project cockpit: card alignment is strange should we remove empty cards?
- [ ]     edit/create: sponsors and institutions must not be mandatory, start with empty list, allow deletion of last entry (same as analysisDataPackages)
- [ ]     edit/create: scripts must not be empty, start with list with one empty entry, do not allow deletion of last entry
- [ ]     edit/create: Hint for title contains "deutsch/englisch" twice: "Geben Sie den deutschen Titel des Analysepakets auf Deutsch ein."
- [ ]     edit/create: the breadcrumb on the top of the page is missing (compare with data package)
- [ ]     edit/create: order of the cards: details, description, authors, data curators, institutions, sponsors, license, scripts, data packages, tags, additional links, attachments
- [ ]     edit/create- title: Error message: "..eines Analysepakets..." s is missing
- [ ]     edit/create - data packages: rename title to "Analysedaten"/"Analysis Data"
- [ ]     edit/create - data packages: "+"-button shows script-tooltip
- [ ]     edit/create - data packages: type-dropdown should be labeled "Art der Daten/Type of Data", dropdown menu has a missing header translation, rename type "Analysiertes Datenpaket" to "FDZ-DZHW Datenpaket"/"FDZ-DZHW Datapackage"
- [ ]     edit/create - data packages - "FDZ-DZHW Datapackage": version and access way are lost if autoselected (choose data package which contains exactly one version and one access way, e.g. "16. Sozialerhebung")
- [ ]     edit/create - data packages - "FDZ-DZHW Datapackage": Use "FDZ-DZHW Datapackage" in label and hint of autocomplete
- [ ]     edit/create - data packages - "FDZ-DZHW Datapackage": error message missing when invalid data package is typed in autocomplete (eg. "adfadf")
- [ ]     edit/create - data packages - "FDZ-DZHW Datapackage": Versionchooser hint: "Bitte wählen Sie eine Version", e is missing
- [ ]     edit/create - data packages - "external Datapackage": Datasource must be a single line input like title (without markdown icon)
- [ ]         edit/create - data packages - "external Datapackage": hint of dataSourceUrl must contain valid example like in additionalLinks
- [ ]     edit/create - data packages - "external Datapackage": Title hint in German contains duplicate "deutsch/englisch"
- [ ]     edit/create - data packages: change order of data packages, up and down buttons are missing
- [ ]     edit/create - data packages - "external Datapackage": error messages "eines externen Datenpakets", s is missing very often
- [ ]     edit/create - scripts: german labels und error messages "Skriptsprache" instead of "Skript Sprache", "Softwarepaket" instead of "Software Paket", "Version des Softwarepakets" instead of "Version of Software Package"
- [ ]     edit/create - scripts: attached file is not displayed anymore of restoring previous version of analysis package
- [ ]     edit/create - data packages - "custom Datapackage": dataSources are called "links" in tooltips
- [ ]     edit/create - scripts: "Please choose the software package**(es)** the script is written for." <- A script is only written for one software package
- [ ]     edit/create - scripts: change order of scripts, up and down buttons are missing
- [ ]     edit/create - dataCurators: Card Title in German must be "Datenkuratierung"

**Comment by rreitmann** [comment]
- [ ] edit/create - scripts: german label must be "Version des Softwarepakets" instead of "Version of Software Package"
- [ ] edit/create - sponsors/institutions: last element must be deletable even if it is empty (see additionalLinks)
- [ ] edit/create - scripts - attachmens: large file upload leads to error, afterwards the filename is visible in the input field and the form is in error state but no input shows an error
- [ ] edit/create - scripts: hint software package "Bitte wählen Sie das/die Softwarepaket ein, für die dieses Skript geschrieben wurde." should be "Bitte wählen Sie das Softwarepaket aus, für das dieses Skript geschrieben wurde."
- [ ] edit/create - analysisDataPackage: after restoring a version with no analysisDataPackage I cannot add one (console shows `TypeError: Cannot read properties of undefined (reading 'push')
    at Controller.$ctrl.addPackage`

**Comment by rreitmann** [comment]
- [ ] project cockpit - publications card: tooltips and email texts are not adjusted to contain analysis packages
- [ ] edit/create - sponsors/institutions: last element must be deletable even if it is empty (see additionalLinks)
- [ ] edit/create - scripts: if I move an empty script up, the view shows a used language, but the model is still empty (saving throws an error)
- [ ]

**Comment by rreitmann** [comment]
- [ ]  edit/create - scripts: if I restore a version with two scripts then script language remains empty
- [ ]  project cockpit: report publication mail has wrong id prefix : "stu-ana01$"

**Comment by rreitmann** [comment]
- [ ] edit/create - analysis data: german hint "Bitte wählen **Sie** die Herkunftsart der Analysedaten aus." ("Sie" is missing)
- [ ] edit/create - institutions/sponsors: If I restore a version with no institutions/sponsors there is an empty institution/sponsor instead on none

**Comment by AndyDaniel1** [comment]
I tested the interface of the analysis package in the cockpit and it's already a quite good implementation. I discovered two issues that should be solved: 

**- add a hint stating that files can only be uploaded after the first save**
   - en: files can be uploaded after the first save ; de: Dateien können nach dem ersten speichern hochgeladen werden
![grafik](https://user-images.githubusercontent.com/17981185/143593241-4e27feb0-2645-4089-b64f-374bd2d39c5d.png)

**- the custom data packages should have the same fields for data source as external data package (link also not mandatory)**
![grafik](https://user-images.githubusercontent.com/17981185/143594737-23892ac8-d1b3-4df7-bd5d-91ba893b653b.png)
 The hint below the field data source should be changed to read as follows (only for custom data packages): en: The data source must be described in more detail here; de: Die Datenquelle muss hier näher beschrieben werden

**Comment by rreitmann** [comment]
@AndyDaniel1 Please retest...

**Comment by AndyDaniel1** [comment]
I retested the issue and everything seems to be fine now except for two details: 

1st: if a data provider creates a custom data package and selects the unavailable option, there should be no access way.    

![grafik](https://user-images.githubusercontent.com/17981185/144237391-7a88748d-ba15-4735-98e2-64730ae83a97.png)

2nd: If a Skript is uploaded it is not displayed anymore, instead a "Durchsuchen"  field and "no file selected" string is shown
![grafik](https://user-images.githubusercontent.com/17981185/144239411-3535e56c-814d-4561-9cde-c655e7217ac2.png)

**Comment by rreitmann** [comment]
@AndyDaniel1 Please retest...

**Comment by AndyDaniel1** [comment]
everything works now as expected thank you 😸 ✔️
