### ISSUE TITLE
As publisher I want to release analysis packages

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#2981]
- create shadow copies
- shadow copies can be hidden
- send metadata to da|ra (but not to VerbundFDB!!!)
- post validation ensures that there is a publication

**Comment by rreitmann** [comment]
- [ ] pin to startpage is not possible for analysis packages -> hide from release dialog

**Comment by AndyDaniel1** [comment]
Since I cannot add publications in the test system, I was not able to test the entire release process. 

The english error message in case of missing publication should read as follows (german message is correct): "The Project with the RDC-ID [ID] **_must_** contain exactly one publication. 
![grafik](https://user-images.githubusercontent.com/17981185/143599093-2b9dc10e-6359-4c02-8cb7-df3d8ea2833b.png)

**Comment by AndyDaniel1** [comment]
✔️ works as expected (incl. hidden shadow copies)
