### ISSUE TITLE
The dataset report should be named the same way we name all other documents.

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3108]
The dataset report should be named the same way we name all other documents.

Using Nacaps as an example:

dsreport-nac2018-ds1.pdf -> nac2018_ds1_DsReport_en.pdf.

![grafik](https://user-images.githubusercontent.com/17981185/177948518-8e9ba509-f945-4580-bb96-cfee96fa0213.png)

**Comment by jgolinowski** [comment]
@AndyDaniel1 Changing the naming scheme for the dataset report works fine for new reports. But all existing files remain untouched after generating reports using that new scheme and have to be deleted manually.

![2022-09-15_09-20](https://user-images.githubusercontent.com/4905420/190350239-c52cbfe2-1bd6-4e93-9882-709955da961b.png)

 Is it sufficient to apply this change only to newly generated dataset reports? Renaming existing files might not be sensible since this involves changing the id of each attachment

**Comment by jgolinowski** [comment]
Just noticed that the current file is deleted automatically before the new one is attached. That query is done by filename - so we could construct a second file object using the old naming scheme to also delete those files when a new dataset report is created.

**Comment by AndyDaniel1** [comment]
@jgolinowski Thanks for the quick fix. For now, applying this to new dataset reports is sufficient. If we wanted to change the naming for all reports from released datasets, it would require a unrelease and re-release, which would have some implications for our versioning I would like to avoid. Long story short, this is a feature for future releases... but the idea of automatically deleting existing reports with "incorrect" file names when a new report is uploaded is still a very good idea. It would be great if you could implement this as well.

**Comment by AndyDaniel1** [comment]
✔️
