### ISSUE TITLE
Metadata of Scripts in Analysispackages

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3221]
- The title of the script should be just the filename (no translation needed). The name of the field should be de: "Dateiname" en:"Filename"
- The field "Skriptsprache" should be renamed in "Sprache der Kommentierungen" "Language of Commentaries"

**Comment by AndyDaniel1** [comment]
The title of the script is now completely missing, that was not the task 😄 

![Image](https://github.com/dzhw/metadatamanagement/assets/17981185/971585ba-6634-4caf-8c9e-7247109771aa)

**Comment by SaCodematix** [comment]
Sorry, then I misunderstood the ticket description. Here is what I understood and implemented:

- In the **editing mode** of the analysis package (the screenshot you posted) there is no field `title/Titel` or `filename/Dateiname`, correct. The `filename/Dateiname` field is not displayed because it could still be unknown if no file is selected yet, and would be read-only since it is set automatically based on the selected file. 
![grafik](https://github.com/dzhw/metadatamanagement/assets/66066952/b7cae534-d1ae-4315-8213-c078dd6ca8fc)

- If the user has a look at the analysis package in the **view mode**, the user can then also see the new field `filename/Dateiname` which "replaced" the previous `title` column.
![grafik](https://github.com/dzhw/metadatamanagement/assets/66066952/00c22b9d-1acb-4b47-b99a-e3821957242c)

**Comment by AndyDaniel1** [comment]
@SaCodematix As we don't upload files in every case we still need a title field that don't has to the file name. But (and this is the difference to the current implementation) we don't need the field to be multilingual (die title is always the same in de and en).   
![Image](https://github.com/dzhw/metadatamanagement/assets/17981185/e8aa8982-1b71-4996-ac95-32dd7eaa64d4)

**Comment by AndyDaniel1** [comment]
@SaCodematix thank you it's almost perfect 😃 . We don't need the column "Dateiname" it's sufficient to have the "Titel" and "Datei" column!

**Comment by AndyDaniel1** [comment]
@AndyDaniel1 @tilovillwock Do we need a database migration rule here, as we have analysis scripts with a German and an English title? The rule should be: Always use the English title.

**Comment by AndyDaniel1** [comment]
@SaCodematix the title is still missing 

![Image](https://github.com/dzhw/metadatamanagement/assets/17981185/2e08724c-1378-4352-99ad-921158e2d61a)

**Comment by SaCodematix** [comment]
This is correct and is due to the fact that the corresponding merge request https://github.com/dzhw/metadatamanagement/pull/3300 has not yet been merged due to pending review.

**Comment by AndyDaniel1** [comment]
In the already saved analysis packages it seems to exist an artifact where the german and english title seems to be saved but cannot be deleted

![grafik](https://github.com/dzhw/metadatamanagement/assets/17981185/aa324d17-9499-4f9c-9909-7c92bd93a31c)
