### ISSUE TITLE
Add further attributes to the related publications

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3249]
The following attributes should be added to the related publications:

- doi (or other identificator / reference link)
- split up source references: Author, Title, Issue, journal

**Comment by tilovillwock** [comment]
> doi (or other identificator / reference link)

A DOI Link attribute seems to be already part of the type as far as I can tell. It seems that many publications simply lack the information. One example that has one: https://metadata.fdz.dzhw.eu/de/publications/pub-Engel.2023?page=1&size=10&type=data_packages

> split up source references: Author, Title, Issue, journal

Could you expand on what needs to be split up? Do you want "Source Reference" to be replaced by Journal and Issue? Do we need to consider other publication types like books?

An example from prod:

<img width="784" alt="Bildschirmfoto 2023-10-23 um 12 30 53" src="https://github.com/dzhw/metadatamanagement/assets/111056906/c38e72d2-e520-471d-9bcc-18e49f7f161a">

@AndyDaniel1

**Comment by AndyDaniel1** [comment]
The source reference as a whole should remain, but next to it we should have separate fields for author, title, issue, journal (all not mandatory). It would be best if I provide the input format for the citations to get a better understanding of it

**Comment by AndyDaniel1** [comment]
Check https://thesauri.cessda.eu/swagger-ui/index.html#/Vocabulary-specific%20methods/get__vocid__search

**Comment by tilovillwock** [comment]
According to @AndyDaniel1 the import process already combines citation attributes into a single "Source Reference" attribute so it should be possible to use this as a starting point. We need to find out if this happens on the frontend or backend.

Furthermore:
* the attributes that were already mentioned are supposed to appear in their provided order before the "Source Reference" attribute
* we also want to a add "Abstract" as an optional attribute

**Comment by tilovillwock** [comment]
@AndyDaniel1 we should discuss whether we need to consider a migration strategy for publications that have already been imported. This could lead to some unexpected outcomes. [As far as I can tell](https://github.com/dzhw/metadatamanagement/blob/dev-2023-2-1/mdm-frontend/src/app/legacy/relatedpublicationmanagement/services/relatedPublicationBuilder.service.js) Journal and Issue are not parsed and stored as separate attributes right now. As such we would have to parse the `sourceReference` Attribute for existing publications hoping that there are no deviations from the common format `<Journal>, <Issue>.`

It would also help if we could get an example Excel-File with relevant BibTex data.

**Comment by tilovillwock** [comment]
Note that publication abstract **has already been implemented** as an optional field:
* https://github.com/dzhw/metadatamanagement/blob/dev-2023-2-1/mdm-frontend/src/app/legacy/relatedpublicationmanagement/views/relatedPublicationDetail.html.tmpl#L24
* https://github.com/dzhw/metadatamanagement/blob/dev-2023-2-1/src/main/java/eu/dzhw/fdz/metadatamanagement/relatedpublicationmanagement/domain/RelatedPublication.java#L89

**Comment by ewolf47** [comment]
@AndyDaniel1 
I added the new attributes to the related publication common-details page. Is the order of attributes correct?
![image](https://github.com/dzhw/metadatamanagement/assets/118182853/8b500809-35fa-4f9b-a829-ff8300d81c64)

Because the excel-file, that is used as import, does not provide any information about "journal" or "issue" I added a request to `https://doi.org/<DOI>` which returns multiple information about the publication. In my opinion, there a two possible fields, that can be used to fill the `journal` attribute. Either `container-title` or `container-title-short`. The latter seems to be just a shorter version of the actual journal name. Here is an example to clarify this: When I request with the doi "`10.1007/s11577-017-0485-7`" which belongs to this publication 

> de Vogel, S. (2017). Wie beeinflussen Geschlecht und Bildungsherkunft den Übergang in individuelle und strukturierte Promotionsformen? KZfSS Kölner Zeitschrift für Soziologie und Sozialpsychologie, 69(3), 437–471. https://doi.org/10.1007/s11577-017-0485-7

the `container-title` contains `KZfSS Kölner Zeitschrift für Soziologie und Sozialpsychologie`, while the `container-title-short` only contains `Köln Z Soziol`. So I decided to take the more detailed `container-title`. Is that in your interest?

**Remark**: If the `DOI`-column of a row in the excel-file, that is used as import, is not filled, there won't be any information about the journal and issue, because the `https://doi.org/<DOI>`-request can not be send.

**Comment by AndyDaniel1** [comment]
Will leave the issue open until #3346 is resolved

**Comment by tilovillwock** [comment]
@AndyDaniel1 since the majority of this functionality has already been deployed to production and we're discussing other possible approaches for extracting the journal and issue attributes in #3346 I think it best to **close this issue** or at the very least **remove it from the test column** on the project board.
