### ISSUE TITLE
Generation of the data set report fails

### ISSUE THREAD

**Issue by AndyDaniel1** [dzhw/metadatamanagement#3326]
The generation of the data set report fails. 

Error message:

![grafik](https://github.com/dzhw/metadatamanagement/assets/17981185/06bb6465-6890-44d1-b183-726d24c5d6d9)

@SaCodematix @tilovillwock @moellerth

**Comment by tilovillwock** [comment]
@AndyDaniel1 @thorsteneuler as far as I can tell the report task error message indicates that there's a rogue unicode character in the dataset as described [here](https://unicodeplus.com/U+009D). This character would be rendered as `` in a modern text editor (e.g. Notepad++ or Visual Studio Code).

I don't really have a good explanation how this particular sequence would end up in a dataset other than that maybe the dataset went through a lossy conversion from e.g. a legacy Windows encoding like ISO-8859-1 to UTF-8. I'm unfortunately not that familiar with SPSS.

**Comment by thorsteneuler** [comment]
@tilovillwock Thank you for the information. I've checked for the rogue unicode character (found 19 of them) and removed them. I'll start the generation of the data set report again with the updated information to check if it works now.

I do have two guesses how this particular character came into the dataset (none due to SPSS). It seems to originated from word in  quotations within sentences in quotations.

**Comment by thorsteneuler** [comment]
@tilovillwock Generation failed again. Are there other rogue characters which I can check for?

**Comment by tilovillwock** [comment]
@thorsteneuler this time the report generation seems to be failing because we've hit some kind of memory limit. I'm still investigating but this might take some time. I'll report back as soon as possible. Sorry for the inconvenience.

**Comment by tilovillwock** [comment]
I finally found a configuration that seems to be able to process the workload. We've deployed a fix to production.

@thorsteneuler your report should be listed now since it went through successfully when I tried it.

@anneweber please try creating a report for `dat-nac2018-ds1` again.

@AndyDaniel1 we should discuss the underlying issues in detail during our next Jour Fixe.

**Comment by AndyDaniel1** [comment]
@tilovillwock thank you!!

**Comment by AndyDaniel1** [comment]
The generation failed again for nac2018

![grafik](https://github.com/dzhw/metadatamanagement/assets/17981185/419d5cef-8235-408b-bc1b-b5d37b7c019d)

**Comment by anneweber** [comment]
@tilovillwock Yes, it seems to work now. :) Thank you! 👍
