### ISSUE TITLE
Update and clean up the variable detail page

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#410]
Update and clean up the variable detail page for the next presentation.

* Remove questionnaire pdf
* ~~Show important information (TODO @kpstephan What are important information?)~~
* Show one histogram and boxplot (if it is possible)
* Link to the conceptual data package page

**Comment by rreitmann** [comment]
- keep only one diagram (ask @anfranken)
- add link static data package page
- remove pdf completely

**Comment by rreitmann** [comment]
@anfranken Please check if the details page looks as **desired at the moment** ;-)

**Comment by anfranken** [comment]
These are only some suggestions:
- I think the user don't need the FDZ-ID of the variable
- Instead of the DAPid the user will be more interested in the Label of this project 
- Instead of the Survey-IDs I would show the label of the survey 
- I would order the elements like this: 1. name of variable, 2. label of the variable,  3. DataType, 4. ScaleLevel, 5. Label of project, 6. label of survey
- I would change field -> attribute
- also I would change the camelcase at the English version

**Comment by rreitmann** [comment]
@anfranken your suggestions have been copied to #459 and will be implemented when this page is redesigned
