### ISSUE TITLE
Change layout of distribution table in variable report

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#446]
Desired format needs to be defined

**Comment by bjhuss** [comment]
Thanks for your proposal. A few remarks in order to create lines in the tables:

1.  The lines of the tables look different in some cases: Sometimes there is a bold line under the description of columns (e.g. variable "hsph2") an sometimes there is a double line (e.g. variable "ws2endja"). They should look equal (you find my suggestion below).

1. please use the package `\usepackage{booktabs}`. This package provides different lines (e.g. `\toprule`,` \midrule`, `\bottomrule`, `\cmidrule`) which look much better than the standard lines provided by LaTeX (e.g. `\hline`, `\cline`). Look  [here](http://ctan.mackichan.com/macros/latex/contrib/booktabs/booktabs.pdf) for the documentation of the package.

1. In my opinion we should place a bold line at the top (`\toprule`) of a table, followed by a single row of column headings, then a dividing rule (`\midrule`).Afterwards we provide the valid values, which are separated from the missing values by another `\midrule`. After the columns of data we should finish with a bold line  (`\bottomrule`). Look [here](http://www.namsu.de/Extra/pakete/Booktabs.html) for a  "minimal example" to create professional lines.

1. By default `\toprule` and `\bottomrule` are very thin. We should set them a bit more thick.

**Comment by dkatzberg** [comment]
* No sums are displayed if there are no missing values
* All sums are displayed if there are no valid values

**Comment by rreitmann** [comment]
- String "Ausfülleinweisung" must be "Ausfüllanweisung"

**Comment by bjhuss** [comment]
- Add `\setlength\heavyrulewidth{0.11em}` to the preamble. This increases the width (better: thickness) of `\toprule` and `\bottomrule` from 0,08em (default) to 0,11em.

**Comment by rreitmann** [comment]
@Andy20 Please test the report...
