### ISSUE TITLE
Validation for uniqueness of question.number in an instrument (questionnaire)

### ISSUE THREAD

**Issue by anfranken** [dzhw/metadatamanagement#501]
We need an error message for this validation.

**Comment by anfranken** [comment]
@rreitmann I'm not sure how I can test this, because every question file have to be named after their number and so the number must be unique because two files couldn't have the same name in a file manager.

**Comment by anfranken** [comment]
If you have the same number in two question there is no validation

**Comment by rreitmann** [comment]
@anfranken We have added two "global" validators for the id pattern and the uniqueness of the number. However due to another bug in spring we currently get only one "global" validation error message even if there are multiple failing validators :-( Please test that you get at least one error message

**Comment by anfranken** [comment]
To test the validation message wasn't possible, because of the [bug](https://jira.spring.io/browse/DATAREST-832).
