### ISSUE TITLE
Add modal error log view triggerred from toast

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#515]

**Comment by rreitmann** [comment]
@anfranken Please test  with #514

**Comment by anfranken** [comment]
If you upload the AQ.abs2005 you got this error: { "serverUsed" : "ds019893.mlab.com:19893" , "ok" : 1 , "n" : 0 , "err" : "E11000 duplicate key error index: CloudFoundry_v6d65vl4_mai3frfk.atomic_questions.$name_1_questionnaireId_1 dup key: { : \"8.1\", : \"abs2005-qu2\" }" , "code" : 11000}; nested exception is com.mongodb.MongoException$DuplicateKey: { "serverUsed" : "ds019893.mlab.com:19893" , "ok" : 1 , "n" : 0 , "err" : "E11000 duplicate key error index: CloudFoundry_v6d65vl4_mai3frfk.atomic_questions.$name_1_questionnaireId_1 dup key: { : \"8.1\", : \"abs2005-qu2\" }" , "code" : 11000}

we need a better error message for that. But at the moment it isn't important, because we will change the AQ-import
