### ISSUE TITLE
Add type of technicalRepresentation (question) to domain model

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#688]
We need the type of the technicalRepresentation (e.g. qml) and the language (e.g. xml).
- [x] adjust domain model (new subobject of question)
- [x] adjust interface description
- [x] adjust validation (string length small)
- [x] Implement Domain Model File
- [x] Update Mapping
- [x] Update Search Document
- [x] adjust details page (copy technical representation to clipboard, show with syntax highlighting)

**Comment by dkatzberg** [comment]
Code Style Highlighter:
https://highlightjs.org/

As Angular Directive:
https://github.com/pc035860/angular-highlightjs

**Comment by dkatzberg** [comment]
Copy to Clipboard:
https://sachinchoolur.github.io/ngclipboard/

**Comment by dkatzberg** [comment]
- [ ] Add Toast for correct copying to clipboard.

**Comment by limouri** [comment]
please check the following points in the technicalRepresentation card:
- [ ] use md-card-content instead of md-content. md-card-content have a padding feature and the     background color is white, so we don't need to set the background color to white.
- [ ] use flex instead of flex-get-sm="100"
- [ ] use a tooltip for the copy button
- [ ] check the horizontal position of elements in the md-card-header
- [ ] use md-divider between header and content

**Comment by dkatzberg** [comment]
@anfranken Please test this detail page. you have to upload by our own a question with a technical representation. I will sent you a mail with an xml example.

**Comment by rreitmann** [comment]
@anfranken Snippets should work when you set the language to "xml". Furthermore you have to escape " with \" and \ with \\.
