### ISSUE TITLE
Implement new Attributes for Survey

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#756]
Implement the model of the new attributes for survey (#739 )
- [x] Update the importer
- [x] Update Domain Object
- [x] Implement Validations (Backend)
- [x] Update Projection
- [x] Update JUnit Object Builder

No update ElasticSearch Mapping, because only numeric values
No update SurveySearchObject, because only numeric values

**Comment by rreitmann** [comment]
@anfranken Please test the new attributes of survey defined in #739

**Comment by anfranken** [comment]
- If you fill responseRate with a wrong double, for example the decimal separator is a comma and not a point or with a letter, you get this unreadable error message:  
 - {{Can not construct instance of java.lang.Double from String value '24,7': not a valid Double value at [Source: org.apache.catalina.connector.CoyoteInputStream@5ba401c2; line: 1, column: 903] (through reference chain: eu.dzhw.fdz.metadatamanagement.surveymanagement.domain.Survey["responseRate"])}}
- You get the same problem if you use letter for “sampleSize” or “grossSampleSize”
- I think there also is no validation for the name of the *.svgs.  Because you can upload files named like you want (e.g. abs2005-sy1_responserate_hurz.svg).  
- Update : 
 - Now you get following error message: "Die Bilddatei '{"path":"surveys/images/abs2005-sy1_responserate_hurz.svg"}' konnte nicht hochgeladen werden!"

**Comment by dkatzberg** [comment]
@rreitmann check the code since anfranken comment.

**Comment by rreitmann** [comment]
@anfranken Please retest the import
