### ISSUE TITLE
Refine relatedPublication details page

### ISSUE THREAD

**Issue by rreitmann** [dzhw/metadatamanagement#771]
- rework related information panel (as defined by @kpstephan)

**Comment by kpstephan** [comment]
please change string "related information" --> related objects (Verbundene Objekte)

related objects: display the links in the following order:
studies (Studien)
datasets (Datensätze)
surveys (Erhebungen)
instruments (Instrumente)
questions (Fragen)
variables (Variablen)

please change string "information of the publication" --> details (Details)

card details: display the following properties in the following order
authors (Autor(inn)en); this property has to be implemented
year of publication (Erscheinungsjahr); this property has to be implemented
citation (Zitation); relatedPublication.sourceReference
DOI; relatedPublication.doi
URL; relatedPublication.sourceLink

add new card with title "abstract" (Abstract)
content of this card in the following order: 
relatedPublication.publicationAbstract
string "source (Quelle)"; this property has to be implemented

**Comment by rreitmann** [comment]
There are two changes in the domain model:
- publicationAbstract is now abstract
- new I18nString abstractSource

**Comment by limouri** [comment]
We can't use "abstract" as a variable name, because it's a java reserved keyword.

**Comment by dkatzberg** [comment]
We should discuss about the field: abstractSource . In my optionen it should be mandatory.

**Comment by dkatzberg** [comment]
@anfranken Please test everything on the page and check the changes.

**Comment by anfranken** [comment]
In the interface you have an field publicationAbstract and abstract. That's confusing and not conform to the domain model

**Comment by limouri** [comment]
@anfranken please read my comment above

**Comment by limouri** [comment]
@anfranken the Domain model and the Intreface are updated

**Comment by anfranken** [comment]
- Interfaces and validation says:
publicationAbstract ->  A complete Abstract. (X-LARGE)
abstractSource.de -> A complete Abstract.DE (LARGE)
abstractSource.en -> A complete Abstract.EN (LARGE)
I really don't get it. You have an abstract in german, english and in a third language which can be longer than the german and english abstract? 
- Also it's a bit confusing if you upload a relatedPublication and everything is fine but you can't find the detail page, because it has no valid related objects. Maybe we need a warning if we upload a relatedPublication without any valid relations.

**Comment by rreitmann** [comment]
I have disabled the publications tab when a project is selected, cause it does not make sense to filter related publications by project. @anfranken Please retest...
