### ISSUE TITLE
Add attachments to data sets

### ISSUE THREAD

**Issue by dkatzberg** [dzhw/metadatamanagement#971]
Actual, there is no possibility to download an compiled dataset report.

- [x] Implement the functionality to download and upload a dataset report

**Comment by rreitmann** [comment]
see #793 for details regarding metadata

**Comment by rreitmann** [comment]
@dkatzberg Here are my first remarks:
- [ ] The Domain Model (wiki) does not contain DataSetAttachmentMetadata
- [ ] Final job complete toast does not show the number of attachments
- [ ] Attachments are currently uploaded in parallel an the next data set upload starts before the previous attachments have been uploaded

**Comment by KeLange** [comment]
- When I upload a dataset without a subdataset the upload doesn't end.
- When I enter a datasetnumber in the subdataset sheet, but the number doesn't exist in the dataset sheet, the upload doesn't end.
- Should the numbers in the protocol dialog display the numbers of uploads I want to have or the number of files which are really uploaded? Actually it is the number of files I want to upload.
- When I upload only one dataset and one attachment the protocol dialog says "Upload von 1 Datensätzen und 1 Anhängen". Could it be singular in this case?
- The number of uploaded subdatasets is missing.
- On the english data set detail page it must be "Type" instead of "Typ".

**Comment by rreitmann** [comment]
@KeLange Please retest the things you have mentioned!
